import mongoose from "mongoose";
const { Schema } = mongoose;

export const twitterDealsSchema = new Schema(
    {
        created_at: String,
        id: Number,
        id_str: String,
        text: String,
        truncated: Boolean,
        entities: {},
        source: String,
        user: {
            id: Number,
            id_str: String,
            name: String,
            screen_name: String,
            location: String,
            description: String,
            url: String,
            entities: {},
            protected: Boolean,
            followers_count: Number,
            friends_count: Number,
            listed_count: Number,
            created_at: String,
            favourites_count: Number,
            verified: Boolean,
            statuses_count: Number,
            profile_background_color: String,
            profile_background_image_url: String,
            profile_background_image_url_https: String,
            profile_background_tile: Boolean,
            profile_image_url: String,
            profile_image_url_https: String,
        },
        geo: Number,
        coordinates: Number,
        place: String,
        contributors: String,
        is_quote_status: Boolean,
        retweet_count: Number,
        favorite_count: Number,
        favorited: Boolean,
        retweeted: Boolean,
        possibly_sensitive: Boolean,
        lang: String,
        entities: {},
    },
    { collection: "twitter_deals" }
);
