export const NUMBER_OF_REQUESTS_PER_YEAR_REQUEST =
    "NUMBER_OF_REQUESTS_PER_YEAR_REQUEST";
export const NUMBER_OF_REQUESTS_PER_YEAR_REQUEST_SUCCESS =
    "NUMBER_OF_REQUESTS_PER_YEAR_REQUEST_SUCCESS";
export const NUMBER_OF_REQUESTS_PER_YEAR_REQUEST_FAILURE =
    "NUMBER_OF_REQUESTS_PER_YEAR_REQUEST_FAILURE";

export const TYPE_OF_SERVICE_REQUESTS_REQUEST =
    "TYPE_OF_SERVICE_REQUESTS_REQUEST";
export const TYPE_OF_SERVICE_REQUESTS_REQUEST_SUCCESS =
    "TYPE_OF_SERVICE_REQUESTS_REQUEST_SUCCESS";
export const TYPE_OF_SERVICE_REQUESTS_REQUEST_FAILURE =
    "TYPE_OF_SERVICE_REQUESTS_REQUEST_FAILURE";

export const ZIPCODE_VS_NUMBER_OF_REQUESTS_REQUEST =
    "ZIPCODE_VS_NUMBER_OF_REQUESTS_REQUEST";
export const ZIPCODE_VS_NUMBER_OF_REQUESTS_REQUEST_SUCCESS =
    "ZIPCODE_VS_NUMBER_OF_REQUESTS_REQUEST_SUCCESS";
export const ZIPCODE_VS_NUMBER_OF_REQUESTS_REQUEST_FAILURE =
    "ZIPCODE_VS_NUMBER_OF_REQUESTS_REQUEST_FAILURE";

export const CITY_VS_TYPE_OF_SERVICE_REQUESTS_REQUEST =
    "CITY_VS_TYPE_OF_SERVICE_REQUESTS_REQUEST";
export const CITY_VS_TYPE_OF_SERVICE_REQUESTS_REQUEST_SUCCESS =
    "CITY_VS_TYPE_OF_SERVICE_REQUESTS_REQUEST_SUCCESS";
export const CITY_VS_TYPE_OF_SERVICE_REQUESTS_REQUEST_FAILURE =
    "CITY_VS_TYPE_OF_SERVICE_REQUESTS_REQUEST_FAILURE";

export const TOP_RATED_SERVICES_REQUEST = "TOP_RATED_SERVICES_REQUEST";
export const TOP_RATED_SERVICES_REQUEST_SUCCESS =
    "TOP_RATED_SERVICES_REQUEST_SUCCESS";
export const TOP_RATED_SERVICES_REQUEST_FAILURE =
    "TOP_RATED_SERVICES_REQUEST_FAILURE";

export const RECOMMENDED_SERVICES_REQUEST = "RECOMMENDED_SERVICES_REQUEST";
export const RECOMMENDED_SERVICES_REQUEST_SUCCESS =
    "RECOMMENDED_SERVICES_REQUEST_SUCCESS";
export const RECOMMENDED_SERVICES_REQUEST_FAILURE =
    "RECOMMENDED_SERVICES_REQUEST_FAILURE";
export const RESET_RECOMMENDED_SERVICES = "RESET_RECOMMENDED_SERVICES";

export const MOST_INFLUENTIAL_BUSINESSES_REQUEST =
    "MOST_INFLUENTIAL_BUSINESSES_REQUEST";
export const MOST_INFLUENTIAL_BUSINESSES_REQUEST_SUCCESS =
    "MOST_INFLUENTIAL_BUSINESSES_REQUEST_SUCCESS";
export const MOST_INFLUENTIAL_BUSINESSES_REQUEST_FAILURE =
    "MOST_INFLUENTIAL_BUSINESSES_REQUEST_FAILURE";

export const MOST_INFLUENTIAL_PEOPLE_REQUEST =
    "MOST_INFLUENTIAL_PEOPLE_REQUEST";
export const MOST_INFLUENTIAL_PEOPLE_REQUEST_SUCCESS =
    "MOST_INFLUENTIAL_PEOPLE_REQUEST_SUCCESS";
export const MOST_INFLUENTIAL_PEOPLE_REQUEST_FAILURE =
    "MOST_INFLUENTIAL_PEOPLE_REQUEST_FAILURE";

export const MOST_INFLUENTIAL_COMMUNITY_REQUEST =
    "MOST_INFLUENTIAL_COMMUNITY_REQUEST";
export const MOST_INFLUENTIAL_COMMUNITY_REQUEST_SUCCESS =
    "MOST_INFLUENTIAL_COMMUNITY_REQUEST_SUCCESS";
export const MOST_INFLUENTIAL_COMMUNITY_REQUEST_FAILURE =
    "MOST_INFLUENTIAL_COMMUNITY_REQUEST_FAILURE";
