export const BUSINESS_DEALS_REQUEST = "BUSINESS_DEALS_REQUEST";
export const BUSINESS_DEALS_REQUEST_SUCCESS = "BUSINESS_DEALS_REQUEST_SUCCESS";
export const BUSINESS_DEALS_REQUEST_FAILURE = "BUSINESS_DEALS_REQUEST_FAILURE";

export const BUSINESSES_REQUEST = "BUSINESSES_REQUEST";
export const BUSINESSES_REQUEST_SUCCESS = "BUSINESSES_REQUEST_SUCCESS";
export const BUSINESSES_REQUEST_FAILURE = "BUSINESSES_REQUEST_FAILURE";

export const GET_BUSINESSES_BY_SERVICE_TYPE = "GET_BUSINESSES_BY_SERVICE_TYPE";

export const SET_FILTER = "SET_FILTER";
export const RESET_FILTER = "RESET_FILTER";
export const FILTER_BUSINESSES = "FILTER_BUSINESSES";

export const REVIEWS_REQUEST = "REVIEWS_REQUEST";
export const REVIEWS_REQUEST_SUCCESS = "REVIEWS_REQUEST_SUCCESS";
export const REVIEWS_REQUEST_FAILURE = "REVIEWS_REQUEST_FAILURE";
export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_REQUEST_SUCCESS = "ADD_REVIEW_REQUEST_SUCCESS";
export const ADD_REVIEW_REQUEST_FAILURE = "ADD_REVIEW_REQUEST_FAILURE";
export const RESET_REVIEWS = "RESET_REVIEWS";
export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_REQUEST_SUCCESS = "DELETE_REVIEW_REQUEST_SUCCESS";
export const DELETE_REVIEW_REQUEST_FAILURE = "DELETE_REVIEW_REQUEST_FAILURE";

export const SET_FILTERED_BUSINESSES = "SET_FILTERED_BUSINESSES";
