export const EVENTS_REQUEST = "EVENTS_REQUEST";
export const EVENTS_REQUEST_SUCCESS = "EVENTS_REQUEST_SUCCESS";
export const EVENTS_REQUEST_FAILURE = "EVENTS_REQUEST_FAILURE";

export const SET_FILTER_TYPE = "SET_FILTER_TYPE";
export const RESET_EVENT_FILTER = "RESET_EVENT_FILTER";
