export const SET_SEARCH_FIELD_REQUEST = "SET_SEARCH_FIELD_REQUEST";

export const FILTER_BUSINESSES_SEARCH_REQUEST =
    "FILTER_BUSINESSES_SEARCH_REQUEST";
export const FILTER_BUSINESSES_SEARCH_REQUEST_SUCCESS =
    "FILTER_BUSINESSES_SEARCH_REQUEST_SUCCESS";
export const FILTER_BUSINESSES_SEARCH_REQUEST_FAILURE =
    "FILTER_BUSINESSES_SEARCH_REQUEST_FAILURE";

export const SET_SEARCH_LOG_CITY_ENTRY = "SET_SEARCH_LOG_CITY_ENTRY";
export const SET_SEARCH_LOG_ZIPCODE_ENTRY = "SET_SEARCH_LOG_ZIPCODE_ENTRY";
export const SET_SEARCH_LOG_BUSINESS_CITY_ENTRY =
    "SET_SEARCH_LOG_BUSINESS_CITY_ENTRY";
export const SET_SEARCH_LOG_BUSINESS_ZIPCODE_ENTRY =
    "SET_SEARCH_LOG_BUSINESS_ZIPCODE_ENTRY";
