export const TWITTER_MATCHES_REQUEST = "TWITTER_MATCHES_REQUEST";
export const TWITTER_MATCHES_REQUEST_SUCCESS =
    "TWITTER_MATCHES_REQUEST_SUCCESS";
export const TWITTER_MATCHES_REQUEST_FAILURE = "SERVICES_REQUEST_FAILURE";
