export const VIEW_ORDER_BY_USER_ID_REQUEST = "VIEW_ORDER_BY_USER_ID_REQUEST";
export const VIEW_ORDER_BY_USER_ID_REQUEST_SUCCESS =
    "VIEW_ORDER_BY_USER_ID_REQUEST_SUCCESS";
export const VIEW_ORDER_BY_USER_ID_REQUEST_FAILURE =
    "VIEW_ORDER_BY_USER_ID_REQUEST_FAILURE";

export const VIEW_ALL_ORDERS_REQUEST = "VIEW_ALL_ORDERS_REQUEST";
export const VIEW_ALL_ORDERS_REQUEST_SUCCESS =
    "VIEW_ALL_ORDERS_REQUEST_SUCCESS";
export const VIEW_ALL_ORDERS_REQUEST_FAILURE =
    "VIEW_ALL_ORDERS_REQUEST_FAILURE";

export const SET_VIEW_ALL_ORDERS = "SET_VIEW_ALL_ORDERS";
